### ISSUE TITLE
Fix overlap of speakercard on mobiles

### ISSUE THREAD

**Issue by thepushkarp** [GDG-GANDHINAGAR/devfest-19#110]
![Screenshot_20191007_231607](https://user-images.githubusercontent.com/42088801/66335351-83414f00-e958-11e9-9351-dc0e92aea414.png)

**Comment by AmanRaj1608** [comment]
Okay I am not it

**Comment by aashutoshrathi** [comment]
@AmanRaj1608 Updates?
