### ISSUE TITLE
Minor improvements

### ISSUE THREAD

**Issue by aashutoshrathi** [GDG-GANDHINAGAR/devfest-19#30]
- ~Increase font size for section header.~
- Make app bar logo clickable and redirect it to home

**Comment by aashutoshrathi** [comment]
@AmanRaj1608 Can you also try doing any of these?

**Comment by samagragupta** [comment]
@aashutoshrathi Design Club says not to increase the font of the section header.

**Comment by aashutoshrathi** [comment]
We have to increase weight, increase it a bit.
Check if that is looking good.
