### ISSUE TITLE
fix speaker page details dialogue layout

### ISSUE THREAD

**Issue by parth181195** [GDG-GANDHINAGAR/devfest-19#33]
![localhost_4200_home](https://user-images.githubusercontent.com/17850142/64081710-562eca80-cd22-11e9-8739-f76c2047e597.png)

**Comment by pAditya198** [comment]
should i remove the gradient and make background simple gray?

**Comment by aashutoshrathi** [comment]
Yes. Plus also, fix the padding issue.

**Comment by pAditya198** [comment]
okay

**Comment by aashutoshrathi** [comment]
More improvements to be done on this like the font on everything in site should be Product Sans.
