### ISSUE TITLE
Footer elements are not aligned on small screens and shows x-overflow on homepage

### ISSUE THREAD

**Issue by thepushkarp** [GDG-GANDHINAGAR/devfest-19#51]
![image](https://user-images.githubusercontent.com/42088801/64233886-cf8d0f80-cf12-11e9-8527-80d4203fdec7.png)

**Comment by thepushkarp** [comment]
There's some x-overflow here too!

**Comment by thepushkarp** [comment]
![image](https://user-images.githubusercontent.com/42088801/64286230-aef8a000-cf7a-11e9-9ea5-cc3e98a47a27.png)

Social Media icons are disaligned too

**Comment by aashutoshrathi** [comment]
Fix this @GDG-GANDHINAGAR/web-dev-team

**Comment by parth181195** [comment]
both are fixed its in my next commit
