### ISSUE TITLE
If user is subscribed, hide subscribe button from home

### ISSUE THREAD

**Issue by aashutoshrathi** [GDG-GANDHINAGAR/devfest-19#86]

**Comment by samagragupta** [comment]
This feature is already there:
![Capture](https://user-images.githubusercontent.com/32234926/65573614-e7433b00-df88-11e9-80f3-9f85a1fe4f79.JPG)

**Comment by thepushkarp** [comment]
![image](https://user-images.githubusercontent.com/42088801/65584989-5d529c80-df9f-11e9-8112-5551948996f6.png)

The button in the contact us section can be made to show unsubscribe and subscribe as the profile page.

**Comment by thepushkarp** [comment]
![image](https://user-images.githubusercontent.com/42088801/65585237-c76b4180-df9f-11e9-982f-cb7cb654fb74.png)

The button in the contact us section can be made to show unsubscribe and subscribe as the button on the profile page.
